Feature/test user tools
surp-hovhannes/bahk pull request #32
Opened 2024-06-29 22:44 UTC by mattash

This adds a new module for the app called "app_management" that can be used to post changelog updates for users to learn more about what changes are being pushed to the app. 

It also adds a button for users to provide feedback and submit bug reports.

2024-07-01 05:27 UTC, andylitalo requested changes
One small question that might need a code change for displaying changelogs when there is none in the database

2024-07-01 05:27 UTC, andylitalo commented on hub/templates/changelog.html
> +  {% for changelog in changelogs %}
In the edge case where there are no changelogs, this loop throws an error. Should we just skip the loop with an `if` block if there are no changelogs, or is the error good as a reminder to populate the changelog field?

2024-07-01 17:43 UTC, mattash commented on hub/templates/changelog.html
> +  {% for changelog in changelogs %}
Good point. I can handle that.

2024-07-01 20:03 UTC, mattash commented on hub/templates/changelog.html
> +  {% for changelog in changelogs %}
fixed here: https://github.com/surp-hovhannes/bahk/pull/32/commits/dfe3ad7e055437f2027c97288fc0e74828a095da

2024-07-02 05:00 UTC, andylitalo approved these changes
LGTM!

2024-07-02 05:01 UTC, merged