Feature/click fast card opens modal
surp-hovhannes/bahk pull request #33
Opened 2024-06-30 01:01 UTC by mattash

Checkout #26

2024-07-01 05:17 UTC, andylitalo commented
Right now, clicking anywhere inside the image on the fast card opens the modal, including the "Join Fast" and "Leave Fast" buttons, so when clicking either button, the modal starts to pop up before the user is redirected. I think we'll need javascript to exclude them from the clickable region (see [here](https://stackoverflow.com/questions/70861330/exclude-child-components-from-div-onclick)).

Holding of from merging for now.

2024-07-01 17:44 UTC, mattash commented
Good catch. I have a good idea how to fix it.

2024-07-01 20:14 UTC, mattash commented
I resolved previous comment in https://github.com/surp-hovhannes/bahk/pull/33/commits/9bb659ce86bdbaf8358c729bb70629e7dff40faf

2024-07-04 04:17 UTC, andylitalo requested changes
Looks like it should work but modal still opens upon button clicks in local testing :(

2024-07-04 04:17 UTC, andylitalo commented on hub/templates/components/fast_card.html
> +    <div class="card mb-3" data-bs-target="#{{ fast.modal_id }}" data-bs-toggle="modal" onclick="if(event.target.tagName !== 'BUTTON' && !event.target.closest('form')) { location.href='#'; }" style="
for some reason the modal still starts to open when I click the Join Fast or Leave Fast buttons, even though you're excluding buttons from the event target tag names...

2024-07-21 00:20 UTC, andylitalo commented
I'm going to approve since I think giving people the ability to learn about the fast by clicking on the card is more valuable than flawless UX :)

2024-07-21 00:21 UTC, andylitalo approved these changes

2024-07-21 00:21 UTC, merged