API Endpoint to Retrieve Church Data
surp-hovhannes/bahk pull request #50
Opened 2024-09-10 02:53 UTC by mattash

Fixes #48

2024-09-12 02:06 UTC, andylitalo requested changes
Just a note about the get_queryset()

2024-09-12 19:33 UTC, andylitalo requested changes
Comment about possible redundancy

2024-09-12 19:34 UTC, andylitalo commented
Sorry for the review spam--still figuring out GitHub's mobile app

2024-09-12 23:18 UTC, mattash commented on hub/views/church.py
> +    def get_queryset(self):
So the way this should work is that a request of /api/churches/ will return a list of all churches in the DB. /api/churches/[ID], will return the information a specific church.

2024-09-13 15:59 UTC, andylitalo commented on hub/views/church.py
> +        return queryset
nit could you reduce to one line `return Church.objects.all()`?

2024-09-13 16:05 UTC, andylitalo commented on hub/views/church.py
> +    def get_queryset(self):
Thanks! Could we include that in the docstring? It currently only describes filtering by `username`, which I'm not sure if this method supports.

2024-09-13 16:05 UTC, andylitalo requested changes
Thanks for the explanation! A few more questions about getting the queryset

2024-09-14 18:37 UTC, andylitalo requested changes
A couple questions

2024-09-14 21:07 UTC, andylitalo approved these changes
Tested church detailed view with condensed queryset param

2024-09-14 21:07 UTC, merged