Profile API endpoint needs to retrieve more user information
surp-hovhannes/bahk pull request #51
Opened 2024-09-10 02:53 UTC by mattash

Fixes #49

2024-09-12 02:06 UTC, andylitalo requested changes
Might be helpful to keep the view as is for future modification and create a new user view

2024-09-12 02:26 UTC, mattash commented on hub/views/profile.py
> +    serializer_class = UserSerializer
It's fine, but on the client side, it would require multiple requests to populate something like the profile page, that needs to display profile info, as well as username and email.

2024-09-12 19:33 UTC, andylitalo commented on hub/views/profile.py
> +    serializer_class = UserSerializer
Ah got it--thanks!

Can we change the serializer "inheritance" so the ProfileSerializer is the one with user + profile data and UserSerializer just contains user data? It'll be clearer if the Profile view uses the ProfileSerializer.

I can make the change tonight if you can't get to it.

2024-09-13 15:52 UTC, andylitalo approved these changes
LGTM! Concise, I like it. Thanks for the changes!

2024-09-13 15:52 UTC, merged